### ISSUE TITLE
功能建议：恢复观看进度

### ISSUE THREAD

**Issue by Xnjikol** [LuckyPuppy514/external-player#1]
使用当前版本的external player，如果先在B站内观看一段时间，再切换到本地播放器，视频会从头开始播放，非常不方便，希望能记住当前网页中的播放进度。

**Comment by LuckyPuppy514** [comment]
![20241129231619](https://github.com/user-attachments/assets/e5be220b-8b20-4467-9c19-d6bbbbf57f77)

最新版已添加
