### ISSUE TITLE
功能建议：添加字幕

### ISSUE THREAD

**Issue by Xnjikol** [LuckyPuppy514/external-player#2]
B站网页版带有字幕，但是在本地播放器中没有（除了内嵌到视频中的外），且无法选择切换开启字幕，对于一些搬运的外文视频非常不方便

**Comment by LuckyPuppy514** [comment]
![20241129231503](https://github.com/user-attachments/assets/757ed561-065f-41a0-b633-326df2bfc30e)

全局设置中可以开启字幕
