### ISSUE TITLE
每次进去页面按钮位置都会重置

### ISSUE THREAD

**Issue by zzhh-zzh** [LuckyPuppy514/external-player#6]
![屏幕截图 2024-12-06 161413](https://github.com/user-attachments/assets/5f2c896e-d826-4167-8cfc-fbac848515fd)
首先设置了按钮位置为0，100
![屏幕截图 2024-12-06 161648](https://github.com/user-attachments/assets/b2391bd2-3332-4f0d-8350-958016d3bb29)
重新进入ye页面之后按钮位置就被重置了，但是在设置里面仍然是0，100

**Comment by LuckyPuppy514** [comment]
你这位置 0，100 好像是正常的位置吧，是像素，不是百分比，或者你拖动到你想要的位置，会自动保存

**Comment by zzhh-zzh** [comment]
在图2这种情况点保存就会跳到图1的情况，但是重新进入这个页面或者其他页面后又会回到图2的情况

**Comment by LuckyPuppy514** [comment]
没明白你意思，你这两张图看起来位置是一样的，设置里面的位置也是一样的
建议你拖动到指定位置，会自动保存位置，千万不要点击保存（因为拖动后，设置里面的数值可能没更新，点击保存就会跑到原来的位置）

**Comment by zzhh-zzh** [comment]
![屏幕截图 2024-12-06 171617](https://github.com/user-attachments/assets/c25dc54c-3484-4dde-b84a-2f9263a56b12)
![屏幕截图 2024-12-06 171646](https://github.com/user-attachments/assets/bb91b09f-6f85-41b8-a5a8-08ff289e16f6)
以任务栏作为参考
上图是刚进入页面的情况，是紧贴任务栏的，看起来应该是0，0 
下图是设置为0，100的情况

**Comment by LuckyPuppy514** [comment]
1. 请拖动到指定位置，让其自动保存，不要点击保存，刷新页面
2.  切换其他网页进行测试

有问题，按数字回复相应的情况，最好附上截图，全屏的

**Comment by zzhh-zzh** [comment]
1拖到指定位置并且自动保存，未打开设置页面点击保存
![屏幕截图 2024-12-06 172827](https://github.com/user-attachments/assets/2307ab12-0d9e-4070-bbd0-7814ec7d610b)
1刷新页面后
![屏幕截图 2024-12-06 173000](https://github.com/user-attachments/assets/41419f92-f94f-4df6-a03c-4e7ac64ebfbf)
2切换到其他页面
![屏幕截图 2024-12-06 173150](https://github.com/user-attachments/assets/49126128-02f6-4717-92a5-d503a7ff1cf5)

**Comment by LuckyPuppy514** [comment]
你这是什么浏览器，看起来不是  edge / chrome， 建议再 edge / chrome 上试试 😢

**Comment by zzhh-zzh** [comment]
噢，这是用chrome内核的心愿浏览器，我用edge试过是可以的，是我浏览器的问题，打扰了
